### ISSUE TITLE
crazy texture error

### ISSUE THREAD

**Issue by Captaindug** [Mirsario/TerrariaOverhaul#121] opened 2022-07-05 16:10 UTC
![error problem thing](https://user-images.githubusercontent.com/108751447/177371142-7ff8b094-656e-44c9-9949-6de131180e31.png) i have a texture error where game textures are on blocks (even maps and things) and i can clean them with mop (im on mac btw)

**Comment by Mirsario** [comment] 2022-07-06 13:47
Duplicate of #118, see my replies there.
Specifically: https://github.com/Mirsario/TerrariaOverhaul/issues/118#issuecomment-1172913693

**Closed as completed by Mirsario** 2022-07-06 13:47 UTC
