### ISSUE TITLE
Scopes do not work (1.4 v5.0 beta 11D)

### ISSUE THREAD

**Issue by RocketBoss360** [Mirsario/TerrariaOverhaul#109] opened 2022-06-20 19:07 UTC
Sniper's in built scope, rifle scope and any other scopes do not do anything when equiped and right clicking, camera stayes centered on player.

**Comment by Mirsario** [comment] 2022-06-21 10:44
Duplicate of #101

**Comment by Mirsario** [comment] 2022-09-01 21:51
Not sure why I didn't close this right away.

**Closed as not planned by Mirsario** 2022-09-01 21:51 UTC
