### ISSUE TITLE
The animation of chopping trees and falling to the ground will affect all trees to refresh and flicker

### ISSUE THREAD

**Issue by xiaoyvyv** [Mirsario/TerrariaOverhaul#230] opened 2024-03-30 18:13 UTC
When I chop down a tree with an axe, at the moment the tree falls, other trees on the screen will flash white. This issue is a must-have in Overhaul-13C, regardless of whether the TML version is 1.3 or 1.4.

**Comment by Mirsario** [comment] 2024-03-31 14:34
Duplicate of #195.

**Closed as not planned by Mirsario** 2024-03-31 14:34 UTC
