### ISSUE TITLE
Broadsword cannot hit anything

### ISSUE THREAD

**Issue by Barerock** [Mirsario/TerrariaOverhaul#154] opened 2022-09-06 03:18 UTC
Broadsword will not hit even grass. I managed to kill a single bunny, but the attack animation doesn't do anything at all to anything else. Heavy hits also do nothing, they don't hit vines or grass or enemies. I'm not even sure I killed the bunny, it probably drowned instead or something. Shortswords work just fine. This was tested with a wood broadsword and tin one. I have Calamity and Stars Above or whatever it's called. I will try removing the directional attacks mod to see if that fixes it.

**Comment by Barerock** [comment] 2022-09-06 03:20
Taking that mod off did nothing, still can't hit anything.

**Comment by Barerock** [comment] 2022-09-06 22:01
Confirmed incompatibility with Calamity, broadswords will not do damage when Calamity is loaded as well. Stars Above still loaded and everything works just fine.

**Comment by Mirsario** [comment] 2022-09-11 15:08
Cannot reproduce. Send me a client.log file from a session where this issue has occurred.
`Install Directory/tModLoader-Logs/client.log`

**Comment by Mirsario** [comment] 2022-12-16 22:01
Nowadays, we have the following "bot tag" in our Discord server for these cases. It's not calamity related.

> If you're experiencing an issue with **inconsistent or barely working melee collision** while using **Terraria Overhaul**, ensure that you do not also have the following mods:
> 
> **CoolerItemVisualEffects** and/or **ArnamentDisplay**
> > These 2 mods (It's actually just two versions of the same mod) needlessly affect melee collision in a way that somehow conflicts and/or takes precedence over Overhaul's gameplay-focused arc-based collision.
> 
> **Directional Melee**
> > This mod may not be as harmful, but is unnecessary when Overhaul is already present.

Closing since there's been no confirmation.

**Closed as not planned by Mirsario** 2022-12-16 22:01 UTC
